### ISSUE TITLE
rawzfitsreader requires GLIBC_2.14

### ISSUE THREAD

**Issue by calispac** [cta-sst-1m/protozfitsreader#47]
Hi all,

I am using the `protozfits` package on a machine on which I don't root privileges. This machine seems to not have the GLIBC_2.14 installed that seems to be required : 

(btw I use this version  https://github.com/cta-sst-1m/protozfitsreader/archive/v1.0.1b1.tar.gz)
```bash
Traceback (most recent call last):
  File "/home/alispach/.miniconda3/envs/digicampipe/bin/digicam-mpe", line 11, in <module>
    load_entry_point('digicampipe', 'console_scripts', 'digicam-mpe')()
  File "/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/alispach/ctasoft/digicampipe/digicampipe/scripts/mpe.py", line 40, in <module>
    from digicampipe.io.event_stream import calibration_event_stream
  File "/home/alispach/ctasoft/digicampipe/digicampipe/io/event_stream.py", line 1, in <module>
    from digicampipe.io import zfits, hdf5, hessio_digicam
  File "/home/alispach/ctasoft/digicampipe/digicampipe/io/zfits.py", line 11, in <module>
    from protozfits.digicam import File
  File "/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/__init__.py", line 2, in <module>
    from .digicam import File as DigicamFile
  File "/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/digicam.py", line 6, in <module>
    from . import rawzfitsreader
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so)
```

Here is a `ldd` of `rawzfitsreader.cpython-36m-x86_64-linux-gnu.so` : 

```bash
(digicampipe) [alispach@login1 digicampipe]$ ldd /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so
/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so)
/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libZFitsIO.so)
/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libACTLCore.so)
/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libprotobuf.so.9)
/home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/rawzfitsreader.cpython-36m-x86_64-linux-gnu.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libzmq.so.4)
        linux-vdso.so.1 =>  (0x00007ffccddc0000)
        libZFitsIO.so => /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libZFitsIO.so (0x00002b17611ac000)
        libstdc++.so.6 => /opt/ebsofts/Core/GCCcore/6.3.0/lib64/libstdc++.so.6 (0x00002b1761577000)
        libm.so.6 => /lib64/libm.so.6 (0x00002b176172c000)
        libgcc_s.so.1 => /opt/ebsofts/Core/GCCcore/6.3.0/lib64/libgcc_s.so.1 (0x00002b17619b0000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00002b17619c8000)
        libc.so.6 => /lib64/libc.so.6 (0x00002b1761be6000)
        libACTLCore.so => /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libACTLCore.so (0x00002b1761f7a000)
        libz.so.1 => /opt/ebsofts/Compiler/GCCcore/6.3.0/zlib/1.2.11/lib/libz.so.1 (0x00002b17622e9000)
        libprotobuf.so.9 => /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libprotobuf.so.9 (0x00002b1762302000)
        /lib64/ld-linux-x86-64.so.2 (0x00002b1760d81000)
        libzmq.so.4 => /home/alispach/.miniconda3/envs/digicampipe/lib/python3.6/site-packages/protozfits/libzmq.so.4 (0x00002b1762613000)
        librt.so.1 => /lib64/librt.so.1 (0x00002b1762864000)
```

```bash
(digicampipe) [alispach@login1 digicampipe]$ ldd --version
ldd (GNU libc) 2.12
Copyright (C) 2010 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

It seems that I could solve this issue by asking the administrator of this machine to install the version 2.14 of GLIBC. So it is not really a problem. To my understanding `rawzfitsreader.cpython-36m-x86_64-linux-gnu.so` was compiled with GLIBC 2.14 which seems to be an old version (see this page https://www.gnu.org/software/libc/). 
So my question is : Should I just ask for GLIBC 2.14 to be installed on the machine I am using (or install it on local) or should/could `rawzfitsreader.cpython-36m-x86_64-linux-gnu.so` be compiled with a more recent GLIBC version ?

Or can we compile the file while installing `protozfits` package. I.e. when `python setup.py install` is executed ?

Thanks in advance

**Comment by Etienne12345** [comment]
I had a similar issue a while ago. It comes from the fact that version 1.0.2 was compiled on Ubuntu by Dominik, which has newer glibc than our old sl6 systems. Yes, 2.14 is pretty old already, but SL6 as an even older version.

No workaround here: you must install the newer version of glibc. 

Alternative workaround: use the fork of version 1.1 instead: I compiled this one on SL6 and it should not need this newer version of glibc.

**Comment by calispac** [comment]
This is related to https://github.com/cta-sst-1m/digicampipe/issues/215
